# Generated by Django 5.1.2 on 2024-12-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categorie_post',
            field=models.ManyToManyField(related_name='categoriepost', to='blog.categoriepost'),
        ),
    ]
