# Generated by Django 5.1.2 on 2024-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoriepost_blogpost_categorie_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
