# Generated by Django 5.1 on 2024-11-16 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proximas_atualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 11, 16, 0, 26, 34, 184049, tzinfo=datetime.timezone.utc))),
                ('descricao', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em Desenvolvimento', 'Em Desenvolvimento'), ('Em Testes', 'Em Testes'), ('Integrado ao sistema', 'Integrado ao sistema')], default='Planejado', max_length=30)),
            ],
        ),
    ]
