# Generated by Django 5.1 on 2024-11-16 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextupdate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proximas_atualizacao',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proximas_atualizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 13, 36, 31, 577500, tzinfo=datetime.timezone.utc)),
        ),
    ]
