# Generated by Django 5.1 on 2024-11-17 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextupdate', '0002_proximas_atualizacao_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximas_atualizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 0, 2, 33, 494183, tzinfo=datetime.timezone.utc)),
        ),
    ]
