# Generated by Django 5.1.2 on 2024-12-05 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextupdate', '0003_alter_proximas_atualizacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximas_atualizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 19, 5, 0, 447196, tzinfo=datetime.timezone.utc)),
        ),
    ]
