# Generated by Django 5.1.2 on 2024-12-06 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextupdate', '0004_alter_proximas_atualizacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proximas_atualizacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 10, 46, 53, 404824, tzinfo=datetime.timezone.utc)),
        ),
    ]
